---

common:
  hostname: mandos
  install_dash: yes
  users:
    - name: jbrubake
      comment: Jeremy Brubaker
      groups:
        - wheel
        - dialout

package_tags:
  - basic
  - extra
  - audio
  - x-basic
  - devel
  - rpmdev

x11:
  terminal: alacritty # Fast, cross-platform, OpenGL terminal emulator | https://crates.io/crates/alacritty
  window_manager: cwm # Calm Window Manager by OpenBSD project         | https://github.com/chneukirchen/cwm
  use_xdm: yes

