---

- name: Install rclone RPM
  become: yes
  dnf:
    name: "{{rclone__url}}"
    state: present
    disable_gpg_check: true

- name: Generate shell completion
  become: yes
  command: rclone completion {{item}}
  loop:
    - bash
    - zsh
    - powershell

