---

copr_repos: # {{{1
  - name: dosbox-x
    repo: rob72/DOSBox-X
  - name: font-manager
    repo: jerrycasiano/FontManager
  - name: lazygit
    repo: atim/lazygit

third_party_repos: # {{{1
  - name: google-earth-pro-stable
    reponame: google-earth
    description: Google Earth
    baseurl: http://dl.google.com/linux/earth/rpm/stable/X86_64
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub

  - name: powershell
    reponame: microsoft
    description: Microsoft
    baseurl: https://packages.microsoft.com/rhel/9/prod/
    gpgkey: https://packages.microsoft.com/rhel/9/prod/repodata/repomd.xml.key
    priority: 99

  - name: wine-stable
    reponame: wine
    description: wine
    baseurl: http://dl.winehq.org/wine-builds/fedora/$releasever
    gpgkey: https://dl.winehq.org/wine-builds/winehq.key

  - name: tofu
    reponame: opentofu
    description: OpenTofu
    baseurl: https://packages.opentofu.org/opentofu/tofu/rpm_any/rpm_any/$basearch
    gpgkey: 
      - https://get.opentofu.org/opentofu.gpg
      - https://packages.opentofu.org/tofu/opentofu.gpg

  - name: terraform
    reponame: terraform
    description: Terraform
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    gpgkey:
      - https://rpm.releases.hashicorp.com/gpg

# URL setup {{{1
#
tea_version_lookup: "{{lookup('ansible.builtin.url', 'https://gitea.com/api/v1/repos/gitea/tea/releases/latest')}}"
tea_url: "{{tea_version_lookup.assets|selectattr('name', 'search', 'linux-amd64.xz$')|map(attribute='browser_download_url')|first}}"

browserpass_version_lookup: "{{lookup('ansible.builtin.url', 'https://api.github.com/repos/browserpass/browserpass-native/releases/latest')}}"
browserpass_url: "{{browserpass_version_lookup.assets|selectattr('name', 'search', 'linux64-.*\\.tar\\.gz$')|map(attribute='browser_download_url')|first}}"

ubi: # {{{1
  - name: drawio
    project: jgraph/drawio-desktop
    regex: drawio-x86_64-.*.AppImage
  - name: signal-cli
    project: AsamK/signal-cli
  - name: sioyek
    project: ahrm/sioyek
    exe: Sioyek-x86_64.AppImage
  - name: tea
    url: "{{tea_url}}"
  - name: yq
    project: mikefarah/yq
  - name: rpg-cli
    project: facundoolano/rpg-cli
  - name: veracrypt
    project: veracrypt/VeraCrypt
    regex: VeraCrypt-.*-x86_64.AppImage
  - name: browsh
    project: browsh-org/browsh
    tag: v1.8.2 # NOTE: v1.8.3 does not have a binary release
  - name: wtf
    project: wtfutil/wtf
  - name: ILSpy
    project: icsharpcode/AvaloniaILSpy # NOTE: Avalonia-based port of ILSpy
    exe: ILSpy
  - name: rclonebrowser
    project: kapitainsky/rclonebrowser

