---

- name: Create storage pool directory
  file:
    path: "{{item}}"
    state: directory
  loop: "{{libvirt__storage_pools|map(attribute='path')}}"

# TODO: Is the shell loop or ansible.posix.acl version better?
# - name: Allow 'qemu' user to access storage pool
#   shell: |
#     p={{item}}
#     while [ "$p" != "$(dirname "{{ansible_user_dir}}")" ]; do
#         setfacl --modify user:qemu:x "$p"
#         p=$(dirname "$p")
#     done
#   loop: "{{libvirt__storage_pools|map(attribute='path')}}"

# # TODO: Host to loop through the parents?
# - name: Allow 'qemu' user to access storage pool
#   ansible.posix.acl:
#     entity: qemu
#   etype: user
#   path: "{{item}}"
#   permissions: x
#   state: present
#   loop: "{{libvirt__storage_pools|map(attribute='path')}}"

- name: Define storage pool
  community.libvirt.virt_pool:
    command: define
    name: "{{pool_name}}"
    xml: "{{lookup('template', 'templates/pool.xml.j2')}}"
    state: present
    uri: qemu:///session
  vars:
    pool_name: "{{item.pool_name}}"
    path: "{{item.path}}"
  loop: "{{libvirt__storage_pools}}"

- name: Start storage pool and enable autostart
  community.libvirt.virt_pool:
    state: active
    autostart: true
    name: "{{item}}"
    uri: qemu:///session
  loop: "{{libvirt__storage_pools|map(attribute='pool_name')}}"

