---

- name: Install packages
  become: yes
  package:
    name: "{{_item}}"
  loop: "{{libvirt__packages}}"
  loop_control:
    loop_var: _item
  notify: Restart libvirtd

- name: Enable libvirtd
  become: yes
  service:
    name: libvirtd
    state: started
    enabled: true

- name: Add users to libvirt group
  become: yes
  user:
    name: "{{_item}}"
    groups: libvirt
    append: yes
  loop: "{{libvirt__users}}"
  loop_control:
    loop_var: _item

- name: Install python3-netaddr for IP manipulation
  become: yes
  package:
    name: python3-netaddr
    state: latest

- name: Define VM networks
  become: yes
  community.libvirt.virt_net:
    name: "{{_item.net_name}}"
    command: define
    xml: "{{lookup('template', 'network.xml.j2')}}"
    state: active
  vars:
    net_name: "{{_item.net_name}}"
    bridge:   "{{_item.bridge}}"
    gw:       "{{_item.address|ansible.utils.ipaddr('address')}}"
    mask:     "{{_item.address|ansible.utils.ipaddr('netmask')}}"
    start:    "{{_item.pool_start}}"
    end:      "{{_item.pool_end}}"
  loop: "{{libvirt__networks}}"
  loop_control:
    loop_var: _item

- name: Autostart VM network
  become: yes
  community.libvirt.virt_net:
    autostart: true
    name: "{{_item}}"
  loop: "{{libvirt__networks|map(attribute='net_name')}}"
  loop_control:
    loop_var: _item

